force-app/main/default/objects/Chainable_Link__c/Chainable_Link__c.object-meta.xml
<CustomObject>
    <label>Chainable Link</label>
    <nameField>
        <label>Job Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chainable Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chainable_Link__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <description>The type of action that was executed by this chain</description>
    <inlineHelpText>The type of action that was executed by this chain</inlineHelpText>
    <label>Action Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Executed_Date__c.field-meta.xml
<CustomField>
    <fullName>Executed_Date__c</fullName>
    <description>The date the action was executed</description>
    <inlineHelpText>The date the action was executed</inlineHelpText>
    <label>Exceuted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The key for this chain.  Must be unique!</description>
    <externalId>true</externalId>
    <inlineHelpText>The key for this chain.  Must be unique!</inlineHelpText>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Last_Link__c.field-meta.xml
<CustomField>
    <fullName>Last_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Signifies that there are no more links being processed</description>
    <inlineHelpText>Signifies that there are no more links being processed</inlineHelpText>
    <label>Last Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Link_Position__c.field-meta.xml
<CustomField>
    <fullName>Link_Position__c</fullName>
    <description>The position this link is in the chain. 0 based</description>
    <inlineHelpText>The position this link is in the chain. 0 based</inlineHelpText>
    <label>Link Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <description>The type of object (serialized) stored in the response</description>
    <inlineHelpText>The type of object (serialized) stored in the response</inlineHelpText>
    <label>Response Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/ChainableVFSupport.cls
/* Author: Charlie Jonas (charlie@callawaycloudconsulting.com)
 *  Description: Remote Action support for client side event emitter library (ChainableHandler.resource)
*/
global class ChainableVFSupport {

    public ChainableVFSupport(ApexPages.StandardController stdController) {}

     @RemoteAction
     global static List<Chainable_Link__c> getJobStatus(String key){
        List<Chainable_Link__c> links = [SELECT Id, Name, Action_Type__c, Key__c, Error__c,
        Response__c, Response_Type__c, Link_Position__c, Last_Link__c, Executed_Date__c, CreatedDate
                FROM Chainable_Link__c
                WHERE Key__c = :key
                ORDER BY Link_Position__c ASC];
        return links;
     }

}