force-app/main/default/objects/Chainable_Link__c/Chainable_Link__c.object-meta.xml
<CustomObject>
    <label>Chainable Link</label>
    <nameField>
        <label>Job Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chainable Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chainable_Link__c/fields/Action_Data__c.field-meta.xml
<CustomField>
    <fullName>Action_Data__c</fullName>
    <description>Actions that were not completed.  Allows chain to be restarted after an error occurs</description>
    <inlineHelpText>Actions that were not completed.  Allows chain to be restarted after an error occurs</inlineHelpText>
    <label>Action_Data</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Action_Type__c.field-meta.xml
<CustomField>
    <fullName>Action_Type__c</fullName>
    <description>The type of action that was executed by this chain</description>
    <inlineHelpText>The type of action that was executed by this chain</inlineHelpText>
    <label>Action Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Continue_on_Exception__c.field-meta.xml
<CustomField>
    <fullName>Continue_on_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if this link will continue execution on an exception</description>
    <inlineHelpText>Determines if this link will continue execution on an exception</inlineHelpText>
    <label>Continue on Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Executed_Date__c.field-meta.xml
<CustomField>
    <fullName>Executed_Date__c</fullName>
    <description>The date the action was executed</description>
    <inlineHelpText>The date the action was executed</inlineHelpText>
    <label>Exceuted Date</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Has_Error__c.field-meta.xml
<CustomField>
    <fullName>Has_Error__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Has Error</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Key__c.field-meta.xml
<CustomField>
    <fullName>Key__c</fullName>
    <description>The key for this chain.  Must be unique!</description>
    <externalId>true</externalId>
    <inlineHelpText>The key for this chain.  Must be unique!</inlineHelpText>
    <label>Key</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Last_Link__c.field-meta.xml
<CustomField>
    <fullName>Last_Link__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Signifies that there are no more links being processed</description>
    <inlineHelpText>Signifies that there are no more links being processed</inlineHelpText>
    <label>Last Link</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Link_Position__c.field-meta.xml
<CustomField>
    <fullName>Link_Position__c</fullName>
    <description>The position this link is in the chain. 0 based</description>
    <inlineHelpText>The position this link is in the chain. 0 based</inlineHelpText>
    <label>Link Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Response_Type__c.field-meta.xml
<CustomField>
    <fullName>Response_Type__c</fullName>
    <description>The type of object (serialized) stored in the response</description>
    <inlineHelpText>The type of object (serialized) stored in the response</inlineHelpText>
    <label>Response Type</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Rollback_on_Exception__c.field-meta.xml
<CustomField>
    <fullName>Rollback_on_Exception__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Determines if DML should be rolled back when an exception occurs during chain execution</description>
    <inlineHelpText>Determines if DML should be rolled back when an exception occurs during chain execution</inlineHelpText>
    <label>Rollback on Exception</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Skip_Processing__c.field-meta.xml
<CustomField>
    <fullName>Skip_Processing__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Don&#39;t process this row. Used for re-running failures</description>
    <inlineHelpText>Don&#39;t process this row. Used for re-running failures</inlineHelpText>
    <label>Skip Processing</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChainableLink.cls
/* Author: Charlie Jonas (charlie@callawaycloudconsulting.com)
 *  Description: DTO Container to allow IChainableAction to be serialized between links
*/
public virtual class ChainableLink{
    public static final String UNPROCESSED_NAME = '[unprocessed]';
    public static final String CLEANUP_NAME = '[cleanup]';

//===LINKING===
    public ChainableLink parent;

//===CONTROL PROPERTIES===
    //continue executing next links even if this action throws an exception. Defaulted to false
    public Boolean continueOnException = false;

    //rolls back any action DML if exception is thrown. Defaulted to true.
    //  Must be set to false if making callouts
    public Boolean rollbackOnException = true;

//===STATE PROPERTIES===
    public Id recordId;
    public String key;
    public String jobId;
    public DateTime executedDate;
    public String response;
    public String responseType;
    public Integer position;
    public String error;
    public Boolean exited;
    public Boolean skipProcessing;

    public Boolean completed {
        get {
            return (error == null && jobId != null);
        }
    }

//===SERIALIZATION DATA===
    public String actionData {get; private set;}
    public String actionTypeString {get; private set;}
    private transient IChainableAction action;

    public ChainableLink(IChainableAction action){
        this.action = action;
        exited = false;
        skipProcessing = false;

        actionData = JSON.serialize(action);
        actionTypeString = action.getType().getName();
    }

    //restore from link
    public ChainableLink(Chainable_Link__c record){
        //action serialization
        actionData = record.Action_Data__c;
        actionTypeString = record.Action_Type__c;

        //control properties
        continueOnException = record.Continue_on_Exception__c;
        rollbackOnException = record.Rollback_on_Exception__c;

        //record details
        recordId = record.Id;
        jobId = record.Name;
        key = record.Key__c;
        position = (Integer) record.Link_Position__c;
        response = record.Response__c;
        responseType = record.Response_Type__c;
        error = record.Error__c;
        exited = record.Last_Link__c;
        skipProcessing = record.Skip_Processing__c;
    }

    public virtual IChainableAction getAction(){
        if(action == null){
            Type actionType = Type.forName(actionTypeString);
            action = (IChainableAction) JSON.deserialize(actionData, actionType);
        }
        return action;
    }

    public virtual Object getResponse(){
        if(response != null && responseType != null){
            Type respType = Type.forName(responseType);
            return JSON.deserialize(actionData, respType);
        }
        return null;
    }


    public Chainable_Link__c toRecord(){
        Chainable_Link__c linkRecord = new Chainable_Link__c(
            Name = (jobId!=null ? jobId : UNPROCESSED_NAME),
            Key__c = key,
            Response__c = response,
            Response_Type__c = getAction().getResponseType().getName(),
            Link_Position__c = position,
            Error__c = error,
            Has_Error__c = !String.isEmpty(error),
            Last_Link__c = exited,
            Action_Data__c = actionData,
            Action_Type__c = actionTypeString,
            Continue_on_Exception__c = continueOnException,
            Rollback_on_Exception__c = rollbackOnException,
            Executed_Date__c = executedDate,
            Id = recordId,
            Skip_Processing__c = skipProcessing
        );
        return linkRecord;
    }
}