force-app/main/default/objects/Chainable_Job__c/Chainable_Job__c.object-meta.xml
<CustomObject>
    <description>Jobs queued up by the Chainable class</description>
    <label>Chainable Job</label>
    <nameField>
        <label>Chainable Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chainable Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Chainable_Link__c/Chainable_Link__c.object-meta.xml
<CustomObject>
    <label>Chainable Link</label>
    <nameField>
        <label>Job Id</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Chainable Links</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Chainable_Link__c/fields/Chainable_Job__c.field-meta.xml
<CustomField>
    <fullName>Chainable_Job__c</fullName>
    <label>Chainable Job</label>
    <referenceTo>Chainable_Job__c</referenceTo>
    <relationshipLabel>Chainable Links</relationshipLabel>
    <relationshipName>Chainable_Links</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Link_Position__c.field-meta.xml
<CustomField>
    <fullName>Link_Position__c</fullName>
    <description>The position this link is in the chain. 0 based</description>
    <inlineHelpText>The position this link is in the chain. 0 based</inlineHelpText>
    <label>Link Position</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Chainable_Link__c/fields/Postponed__c.field-meta.xml
<CustomField>
    <fullName>Postponed__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Checked when the link cannot be executed due to no resource availability.  Will be picked up by the clean-up scheduable</description>
    <inlineHelpText>Checked when the link cannot be executed due to no resource availability.Will be picked up by the clean-up scheduable</inlineHelpText>
    <label>Postponed</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/ChainableCleanupSchedulable.cls
//Schedulable class that cleans up any chains that could not process in realtime due to limits
global class ChainableCleanupSchedulable implements Schedulable {

    global void execute(SchedulableContext sc) {
		for(Chainable_Link__c startingLink : [SELECT Chainable_Job__c, Link_Position__c
                                                FROM Chainable_Link__c
                                                WHERE Postponed__c = true
                                                LIMIT :Limits.getLimitQueueableJobs()]){
            Chainable ch = Chainable.restoreChain(startingLink.Chainable_Job__c, Integer.valueOf(startingLink.Link_Position__c));
            ch.enqueue();
        }
	}
}